Fix bug due to change of glsclient.GlsUtil() signature following use of claritypy-client library
OperationalError: could not translate host name "lims" to address: Name
or service not known